#pragma once
enum mode_names
{
    REMOVE_SPECIAL_CHARACTERS = 1,
    EMAILS_TO_USERNAME,
    USERNAMES_TO_EMAIL,
    APPEND_TO_END,
    APPEND_TO_USERNAME,
    TO_LOWER_CASE,
    TO_UPPER_CASE,
    SWAP_PASS_CASE_FIRST_LETTER,
    SWAP_PASS_NUMBERS_TO_USER,
    SWAP_USER_NUMBER_TO_PASS,
    EXTRACT_X_FROM_PASS,
    SWAP_NUMBERS,
    DELETE_DUPLICATES,
};
